language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: pip install -r requirements.txt --use-mirrors
# command to run tests
script: python peopleflow_tests.py
env:
  - PEOPLEFLOW_ENV=test
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
